site_name: Appendices and Documentation
site_description: Appendices, Manual and API Documentation for IBM AR Business Card
site_author: UCL Computer Science System Engineering 2020 Team 13

theme:
  name: "material"
  language: "en"
  logo:
    icon: "memory"
  palette:
    primary: "deep purple"
    accent: "deep purple"
  feature:
    tabs: true

repo_name: IBM-AR-CARD/API-Doc
repo_url: https://github.com/IBM-AR-CARD/API-Documentation/

copyright: "Copyright &copy; 2019 - 2020 IBM & UCL CS Team 13"

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.def_list
  - codehilite:
      guess_lang: false
  - pymdownx.inlinehilite
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences

nav:
  - API Documentation:
      - Welcome: index.md
      - User Authentication: Authentication.md
      - User Profile: Profile-API.md
      - Chat Conversation API: Conversation-API.md
      - User History Cards: History-API.md
      - User Favourite Cards: Favorite-API.md
      - File Upload: File-Upload.md
  - Deployment Manual:
      - Deploy Flutter: Deploy-Flutter.md
      - Deploy Vue: Deploy-Vue.md
      - Deploy Express: Deploy-Express.md

extra_css:
  - "stylesheets/style.css"

google_analytics:
  - "UA-113940817-4"
  - "auto"
